### ISSUE TITLE
compilation issue

### ISSUE THREAD

**Issue by hotelzululima** [bigjosh/SimpleNeoPixelDemo#1]
following error messages were elicited when I attempted to compile the demo program

Arduino: nightly (Mac OS X), Board: "Arduino Duemilanove or Diecimila, ATmega328"

sketch_may20b.ino: In function 'void sendBit(bool)':
sketch_may20b:56: error: '__builtin_avr_delay_cycles' was not declared in this scope
sketch_may20b:66: error: '__builtin_avr_delay_cycles' was not declared in this scope
sketch_may20b.ino: In function 'void show()':
sketch_may20b:126: error: '__builtin_avr_delay_cycles' was not declared in this scope

  putting in the following at prior to line 42 fixes same:

 #ifndef __builtin_avr_delay_cycles
void __builtin_avr_delay_cycles(unsigned long __n) {
while(__n)
__n--;
}
#endif

**Comment by bigjosh** [comment]
I just updated the code so it now compiles and works correctly under OSX with the Arduino 1.6.1 IDE. I should also work with any past or future version since I am no longer using the problematic _delay_cycles() function.
