### ISSUE TITLE
ESP8266 / Wemos D1 Help?

### ISSUE THREAD

**Issue by thoughtfulhedon** [bigjosh/SimpleNeoPixelDemo#13]
I'm having a devil of a time getting this to work on my Wemos D1 ESP8266 board and wondering if you might be interested in helping me out :) I tried the original code and kept getting undefined errors relating to "_SFR_IO_ADDR". I tried the SimpleNeopixel library and after sorting "no such file or directory" errors by placing the library files in the sketch folder I'm getting  "Error compiling for board" errors. I am a bit of a newb but I'm generally able to follow complex directions... thanks!

**Comment by bigjosh** [comment]
Sorry this code will never work on an ESP. From the FAQ:

> Q: This code does not compile for my [you not-Arduino-Uno board here]!
> 
> A: This code is hand crafted specifically for the chip on the Arduino Uno. It is very unlikely to work with any other chip, and therefore boards that uses a different chip. It is probably possible to get it working with other chips in the AVR8 family, but would take work. For other kinds of chips, you would need a completely different strategy.
