### ISSUE TITLE
License file?

### ISSUE THREAD

**Issue by hansdude** [bigjosh/SimpleNeoPixelDemo#4]
Hi! Thanks for the great library and amazing writeup!

Would you mind providing an explicit open source license of your choice on the repository?

Here's an easy license guide to make the choice simple: http://choosealicense.com/

Otherwise people technically aren't allowed to use it :(. The link above has an explanation of why.

Thanks!

**Comment by bigjosh** [comment]
MIT licence added. Thanks. -josh
