### ISSUE TITLE
Any way to convert this for Teensy 3.6?

### ISSUE THREAD

**Issue by GhostToast** [bigjosh/SimpleNeoPixelDemo#9]
I recently upgraded to a Teensy 3.6 and am unable to compile this sketch. https://gist.github.com/GhostToast/c244ca4786cb3aee867161d9da998826 Any ideas would be greatly appreciated!

**Comment by bigjosh** [comment]
This code is very specifically written to directly access the hardware of the the AVR microprocessor like the ones used on traditional (Uno) Arduino boards. It is not at all portable to other platforms or kinds of processors. 

Luckily the Teensy has it own very very nice way to drive Neopixels...
https://www.pjrc.com/teensy/td_libs_OctoWS2811.html
